x1=int(input("Digite vector x2: "))
y1=int(input("Digite vector x1: "))
x2=int(input("Digite vector y2: "))
y2=int(input("Digite vector 1: "))
d=((x2-x1)**2+(y2-y1)**2)**(1/2)
print("la distancia euclidia entre los puntos es: ", d)